In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Org Chart Overhaul\OfficeSpace.csv")
df

          Employee Name         Manager Name
0         Bill Lumbergh                  NaN
1           Bob Slydell        Bill Lumbergh
2            Bob Porter        Bill Lumbergh
3      Linda M. Grayson        Bill Lumbergh
4          Dom Portwood     Linda M. Grayson
5     Wendy L. Hargrove     Linda M. Grayson
6         Tom Smykowski     Linda M. Grayson
7        Nathan R. Ross     Linda M. Grayson
8         Peter Gibbons         Dom Portwood
9    Cheryl T. Ackerman        Peter Gibbons
10  Samir Nagheenanajar         Dom Portwood
11       Michael Bolton  Samir Nagheenanajar
12     Nathan C. Carter         Dom Portwood
13        Lydia Bennett     Nathan C. Carter
14       Greg S. Torres     Nathan C. Carter
15      Alice L. Munroe     Nathan C. Carter
16        Peggy Carlson    Wendy L. Hargrove
17        Anne Martinez    Wendy L. Hargrove
18       Fred Wilkinson    Wendy L. Hargrove
19    Derek P. Phillips        Tom Smykowski
20      Sarah J. Greene    Derek P. Phillips
21     Alan B. Peterson       Nathan R. Ross
22     Maria D. Sanchez     Alan B. Peterson
23    Bobbie K. Jenkins     Alan B. Peterson
24       Milton Waddams        Tom Smykowski

In [6]:
df["reporting_hierarchy"] = ""
for i in df.index:
    last_manager = df.loc[i,"Manager Name"]
    managers = [df.loc[i,"Employee Name"], last_manager]
    while not pd.isna(last_manager):
        for j in df.index:
            if last_manager == df.loc[j,"Employee Name"]:
                last_manager = df.loc[j,"Manager Name"]
                managers.append(last_manager)
                break
    df.loc[i, "reporting_hierarchy"] = managers[-2]
    for m in range(-3, -len(managers)-1, -1):
        df.loc[i, "reporting_hierarchy"] += " > " + managers[m]
df

,Employee Name,Manager Name,reporting_hierarchy
0,Bill Lumbergh,NaN,Bill Lumbergh
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...

In [8]:
df["direct_reports"] = df["Employee Name"].apply(lambda x: (df["Manager Name"] == x).sum())
df

,Employee Name,Manager Name,reporting_hierarchy,direct_reports
0,Bill Lumbergh,NaN,Bill Lumbergh,3
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,0
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,0
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson,4
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood,3
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,3
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski,2
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross,1
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,3
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,1
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,2
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0

In [11]:
df["total_reports"] = df["reporting_hierarchy"].apply(lambda x: (df["reporting_hierarchy"].str.startswith(x)).sum()) - 1
df

,Employee Name,Manager Name,reporting_hierarchy,direct_reports,total_reports
0,Bill Lumbergh,NaN,Bill Lumbergh,3,24
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,0,0
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,0,0
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson,4,21
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood,3,8
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,3,3
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski,2,3
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross,1,3
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1,1
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0,0
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1,1
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0,0
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,3,3
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0,0
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0,0
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0,0
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0,0
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0,0
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0,0
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,1,1
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0,0
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,2,2
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0,0
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0,0
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0,0