In [1]:
import pandas as pd
from pandas import DataFrame

df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Making The Cut\marathon-data.csv")
df.head()

   age gender     split     final
0   33      M  01:05:38  02:08:51
1   32      M  01:06:26  02:09:28
2   31      M  01:06:49  02:10:42
3   38      M  01:06:16  02:13:45
4   31      M  01:06:32  02:13:59

In [4]:
from numpy import select
count_all = len(df)

# df["final"] = pd.to_datetime(df["final"], format="%H:%M:%S")
conditions =[
    df["final"] < "03:00:00",
    df["final"] < "03:30:00",
    df["final"] < "04:00:00",
    df["final"] < "04:30:00",
    df["final"] < "05:00:00",
    df["final"] < "05:30:00"
]
choices = [
    "sub 3:00:00",
    "3:00:00-3:30:00",
    "3:30:00-4:00:00",
    "4:00:00-4:30:00",
    "4:30:00-5:00:00",
    "5:00:00-5:30:00"
]
df["finish_band"] = select(conditions, choices, default="6:00:00+")
df.head()

   age gender     split     final  finish_band
0   33      M  01:05:38  02:08:51  sub 3:00:00
1   32      M  01:06:26  02:09:28  sub 3:00:00
2   31      M  01:06:49  02:10:42  sub 3:00:00
3   38      M  01:06:16  02:13:45  sub 3:00:00
4   31      M  01:06:32  02:13:59  sub 3:00:00

In [8]:
df_count = (
    df.groupby("finish_band")
    .agg(runners = ('gender', "count"))
)
df_count["% of field"] = (df_count["runners"] * 100/ count_all).round(2)
df_count.sort_values(by= "finish_band")
df_count

                 runners  % of field
finish_band
3:00:00-3:30:00     3038        8.16
3:30:00-4:00:00     4879       13.10
4:00:00-4:30:00     6374       17.11
4:30:00-5:00:00     6766       18.16
5:00:00-5:30:00     6326       16.98
6:00:00+            8902       23.90
sub 3:00:00          965        2.59