In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Hotel Bookings\hotel_bookings.csv", parse_dates=["booking_date", "cancel_date", "checkin_date", "checkout_date"])
df.head(30)

,booking_id,booking_date,cancel_date,checkin_date,checkout_date,is_canceled
0,1,2014-03-18,NaT,2016-02-25,2016-03-24,0
1,2,2014-04-18,NaT,2015-10-02,2015-10-11,0
2,3,2014-04-30,NaT,2015-08-03,2015-08-10,0
3,4,2014-04-30,NaT,2015-08-03,2015-08-10,0
4,5,2014-04-30,NaT,2015-08-03,2015-08-10,0
5,6,2014-06-09,NaT,2015-07-08,2015-07-15,0
6,7,2014-06-30,2015-05-19,2015-07-03,2015-07-13,1
7,8,2014-07-04,NaT,2015-07-03,2015-07-13,0
8,9,2014-07-08,NaT,2015-07-09,2015-07-16,0
9,10,2014-08-13,NaT,2015-07-03,2015-07-17,0
10,11,2014-08-16,NaT,2015-09-01,2015-09-15,0
11,12,2014-08-22,NaT,2015-09-08,2015-09-22,0
12,13,2014-08-26,2015-03-05,2015-07-13,2015-07-18,1
13,14,2014-08-31,NaT,2015-07-14,2015-07-20,0
14,15,2014-09-05,NaT,2015-07-17,2015-07-20,0
15,16,2014-09-07,NaT,2015-08-02,2015-08-16,0
16,17,2014-09-09,2015-04-23,2015-08-02,2015-08-16,1
17,18,2014-09-09,NaT,2015-08-03,2015-08-07,0
18,19,2014-09-10,NaT,2015-07-11,2015-07-17,0
19,20,2014-09-13,NaT,2015-08-31,2015-09-11,0
20,21,2014-09-14,NaT,2015-09-05,2015-09-19,0
21,22,2014-09-15,2015-07-21,2015-07-24,2015-08-07,1
22,23,2014-09-16,NaT,2015-07-24,2015-08-07,0
23,24,2014-09-18,2015-03-25,2015-07-07,2015-07-14,1
24,25,2014-09-18,2015-08-14,2015-08-30,2015-09-11,1
25,26,2014-09-22,NaT,2015-09-12,2015-09-20,0
26,27,2014-09-26,NaT,2015-09-15,2015-09-29,0
27,28,2014-09-27,NaT,2015-07-20,2015-07-30,0
28,29,2014-09-27,NaT,2015-07-20,2015-07-30,0
29,30,2014-09-29,2015-03-25,2015-07-25,2015-08-01,1

In [2]:
df = df.query("is_canceled==0")
df.drop(columns=["is_canceled", "cancel_date", "booking_id", "booking_date"], inplace=True)
df.head(30)

   checkin_date checkout_date
0    2016-02-25    2016-03-24
1    2015-10-02    2015-10-11
2    2015-08-03    2015-08-10
3    2015-08-03    2015-08-10
4    2015-08-03    2015-08-10
5    2015-07-08    2015-07-15
7    2015-07-03    2015-07-13
8    2015-07-09    2015-07-16
9    2015-07-03    2015-07-17
10   2015-09-01    2015-09-15
11   2015-09-08    2015-09-22
13   2015-07-14    2015-07-20
14   2015-07-17    2015-07-20
15   2015-08-02    2015-08-16
17   2015-08-03    2015-08-07
18   2015-07-11    2015-07-17
19   2015-08-31    2015-09-11
20   2015-09-05    2015-09-19
22   2015-07-24    2015-08-07
25   2015-09-12    2015-09-20
26   2015-09-15    2015-09-29
27   2015-07-20    2015-07-30
28   2015-07-20    2015-07-30
31   2015-09-05    2015-09-15
33   2015-08-07    2015-08-10
34   2015-08-15    2015-08-22
36   2015-09-01    2015-09-07
39   2015-09-10    2015-09-20
47   2015-09-07    2015-09-14
48   2015-09-07    2015-09-14

In [3]:
print(f"start: {min(df['checkin_date'])}")
print(f"end: {max(df['checkout_date'])}")

start: 2015-07-01 00:00:00
end: 2017-09-14 00:00:00

In [4]:
dates = pd.date_range(start="2015-07-01", end="2017-09-13")
df_dates = pd.DataFrame(dates, columns=["date"])
df_dates.head(20)

         date
0  2015-07-01
1  2015-07-02
2  2015-07-03
3  2015-07-04
4  2015-07-05
5  2015-07-06
6  2015-07-07
7  2015-07-08
8  2015-07-09
9  2015-07-10
10 2015-07-11
11 2015-07-12
12 2015-07-13
13 2015-07-14
14 2015-07-15
15 2015-07-16
16 2015-07-17
17 2015-07-18
18 2015-07-19
19 2015-07-20

In [10]:
df_dates["rooms_available"] = 200
df_dates["occupied_rooms"] = df_dates["date"].apply(
    lambda x: ((df["checkin_date"] <= x) & (x < df["checkout_date"])).sum()
)
df_dates.head(30)

         date  rooms_available  occupied_rooms
0  2015-07-01              200              35
1  2015-07-02              200              63
2  2015-07-03              200              80
3  2015-07-04              200             107
4  2015-07-05              200             121
5  2015-07-06              200             141
6  2015-07-07              200             152
7  2015-07-08              200             157
8  2015-07-09              200             167
9  2015-07-10              200             177
10 2015-07-11              200             174
11 2015-07-12              200             173
12 2015-07-13              200             178
13 2015-07-14              200             180
14 2015-07-15              200             182
15 2015-07-16              200             179
16 2015-07-17              200             175
17 2015-07-18              200             178
18 2015-07-19              200             172
19 2015-07-20              200             179
20 2015-07-21              200             181
21 2015-07-22              200             183
22 2015-07-23              200             181
23 2015-07-24              200             180
24 2015-07-25              200             184
25 2015-07-26              200             167
26 2015-07-27              200             182
27 2015-07-28              200             179
28 2015-07-29              200             182
29 2015-07-30              200             178

In [14]:
df_dates["yy-mm"] = df_dates["date"].apply(lambda x: str(x)[ :7])
df_dates["occupancy_rate"] = (df_dates["occupied_rooms"] * 100 / df_dates["rooms_available"]).round(2)
df_dates.head(30)

         date  rooms_available  occupied_rooms    yy-mm  occupancy_rate
0  2015-07-01              200              35  2015-07            17.5
1  2015-07-02              200              63  2015-07            31.5
2  2015-07-03              200              80  2015-07            40.0
3  2015-07-04              200             107  2015-07            53.5
4  2015-07-05              200             121  2015-07            60.5
5  2015-07-06              200             141  2015-07            70.5
6  2015-07-07              200             152  2015-07            76.0
7  2015-07-08              200             157  2015-07            78.5
8  2015-07-09              200             167  2015-07            83.5
9  2015-07-10              200             177  2015-07            88.5
10 2015-07-11              200             174  2015-07            87.0
11 2015-07-12              200             173  2015-07            86.5
12 2015-07-13              200             178  2015-07            89.0
13 2015-07-14              200             180  2015-07            90.0
14 2015-07-15              200             182  2015-07            91.0
15 2015-07-16              200             179  2015-07            89.5
16 2015-07-17              200             175  2015-07            87.5
17 2015-07-18              200             178  2015-07            89.0
18 2015-07-19              200             172  2015-07            86.0
19 2015-07-20              200             179  2015-07            89.5
20 2015-07-21              200             181  2015-07            90.5
21 2015-07-22              200             183  2015-07            91.5
22 2015-07-23              200             181  2015-07            90.5
23 2015-07-24              200             180  2015-07            90.0
24 2015-07-25              200             184  2015-07            92.0
25 2015-07-26              200             167  2015-07            83.5
26 2015-07-27              200             182  2015-07            91.0
27 2015-07-28              200             179  2015-07            89.5
28 2015-07-29              200             182  2015-07            91.0
29 2015-07-30              200             178  2015-07            89.0

In [15]:
df_monthly = (
    df_dates
    .groupby("yy-mm")
    .agg({"occupancy_rate": "mean"}).round(2)
)
df_monthly

         occupancy_rate
yy-mm
2015-07           79.74
2015-08           89.63
2015-09           90.47
2015-10           77.89
2015-11           54.92
2015-12           43.26
2016-01           34.13
2016-02           52.21
2016-03           69.66
2016-04           77.53
2016-05           85.76
2016-06           89.52
2016-07           88.56
2016-08           90.47
2016-09           89.22
2016-10           86.66
2016-11           67.53
2016-12           52.05
2017-01           50.48
2017-02           65.62
2017-03           81.27
2017-04           82.25
2017-05           86.77
2017-06           87.40
2017-07           89.26
2017-08           90.39
2017-09           19.69