In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Coffee Sales MoM\coffee_shop_sales.csv", parse_dates=["date"])

In [4]:
df.head(20)

,order_id,date,store,product,quantity,sales
0,1,2023-01-01,Lower Manhattan,Gourmet brewed coffee,2,6.00
1,2,2023-01-01,Lower Manhattan,Brewed Chai tea,2,6.20
2,3,2023-01-01,Lower Manhattan,Hot chocolate,2,9.00
3,4,2023-01-01,Lower Manhattan,Drip coffee,1,2.00
4,5,2023-01-01,Lower Manhattan,Brewed Chai tea,2,6.20
5,6,2023-01-01,Lower Manhattan,Scone,1,3.00
6,7,2023-01-01,Lower Manhattan,Drip coffee,1,2.00
7,8,2023-01-01,Lower Manhattan,Gourmet brewed coffee,2,4.00
8,9,2023-01-01,Lower Manhattan,Barista Espresso,1,4.25
9,10,2023-01-01,Lower Manhattan,Hot chocolate,2,7.00
10,11,2023-01-01,Lower Manhattan,Brewed Chai tea,1,2.55
11,12,2023-01-01,Lower Manhattan,Gourmet brewed coffee,2,7.00
12,13,2023-01-01,Lower Manhattan,Brewed Black tea,1,3.00
13,14,2023-01-01,Lower Manhattan,Brewed Chai tea,1,3.10
14,15,2023-01-01,Lower Manhattan,Barista Espresso,2,6.00
15,16,2023-01-01,Lower Manhattan,Brewed Green tea,2,6.00
16,17,2023-01-01,Lower Manhattan,Scone,1,3.75
17,18,2023-01-01,Hell's Kitchen,Brewed herbal tea,1,2.50
18,19,2023-01-01,Hell's Kitchen,Hot chocolate,2,9.00
19,20,2023-01-01,Hell's Kitchen,Hot chocolate,1,4.75

In [7]:
df["month"] = df["date"].dt.month
df_monthly = (
    df.groupby(["month", "store"])
    .agg({"sales": "sum"})
)
df_monthly

                          sales
month store
1     Astoria          27313.66
      Hell's Kitchen   27820.65
      Lower Manhattan  26543.43
2     Astoria          25105.34
      Hell's Kitchen   25719.80
      Lower Manhattan  25320.05
3     Astoria          32835.43
      Hell's Kitchen   33110.57
      Lower Manhattan  32888.68
4     Astoria          39477.61
      Hell's Kitchen   40304.14
      Lower Manhattan  39159.33
5     Astoria          52428.76
      Hell's Kitchen   52598.93
      Lower Manhattan  51700.07
6     Astoria          55083.11
      Hell's Kitchen   56957.08
      Lower Manhattan  54445.69

In [10]:
df_monthly["prv_month"] = df_monthly.groupby("store")["sales"].shift(1)
df_monthly["MoM"] = df_monthly["sales"] - df_monthly["prv_month"]
df_monthly

                          sales  prv_month       MoM
month store
1     Astoria          27313.66        NaN       NaN
      Hell's Kitchen   27820.65        NaN       NaN
      Lower Manhattan  26543.43        NaN       NaN
2     Astoria          25105.34   27313.66  -2208.32
      Hell's Kitchen   25719.80   27820.65  -2100.85
      Lower Manhattan  25320.05   26543.43  -1223.38
3     Astoria          32835.43   25105.34   7730.09
      Hell's Kitchen   33110.57   25719.80   7390.77
      Lower Manhattan  32888.68   25320.05   7568.63
4     Astoria          39477.61   32835.43   6642.18
      Hell's Kitchen   40304.14   33110.57   7193.57
      Lower Manhattan  39159.33   32888.68   6270.65
5     Astoria          52428.76   39477.61  12951.15
      Hell's Kitchen   52598.93   40304.14  12294.79
      Lower Manhattan  51700.07   39159.33  12540.74
6     Astoria          55083.11   52428.76   2654.35
      Hell's Kitchen   56957.08   52598.93   4358.15
      Lower Manhattan  54445.69   51700.07   2745.62