In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Lesson Streak\LessonStreaks.csv", parse_dates=["date"])
df.head(30)

         id  lesson_id       date    user_id        user_name
0   7830319    7643543 2025-05-01  205139497        Ike Pivot
1   7830320   54486981 2025-05-01  210895353    Inosuke Ortiz
2   7830321    6713046 2025-05-01  188456341  Hermione Miller
3   7830322   46804517 2025-05-01  191335864     Piper Palmer
4   7830323   12624656 2025-05-01  188981754    Indy Maverick
5   7830324    6723930 2025-05-01  209588409    Vegeta Organa
6   7830325   34286031 2025-05-01  173810415  Miles Targaryen
7   7830326    7643534 2025-05-01  205139497        Ike Pivot
8   7830327   58099477 2025-05-01  221324630       Kai Bailey
9   7830328   16537004 2025-05-01  101731126       Goku Ortiz
10  7830329    7644743 2025-05-01  125948590     Diana Nelson
11  7830330   54486985 2025-05-01  210895353    Inosuke Ortiz
12  7830331   12624715 2025-05-01  200414107       Maya Perez
13  7830332    7644744 2025-05-01   34006454      Sara Arnold
14  7830333   46804584 2025-05-01  191335864     Piper Palmer
15  7830334    7644740 2025-05-01   46994177     Rhodey Wells
16  7830336   16536180 2025-05-01  208450551        Sara Ford
17  7830337    7644820 2025-05-01  213946629     Ivy Mcdonald
18  7830338   34286043 2025-05-01  173810415  Miles Targaryen
19  7830339   58099517 2025-05-01  221324630       Kai Bailey
20  7830340   60297973 2025-05-01  221670783      Loki Miller
21  7830341    7643537 2025-05-01  205139497        Ike Pivot
22  7830342   46804590 2025-05-01  191335864     Piper Palmer
23  7830343   60307020 2025-05-01  221318185       Zeke Mason
24  7830344   34287806 2025-05-01   87295251  Hinata Ferguson
25  7830345   54626219 2025-05-01  210895353    Inosuke Ortiz
26  7830346    7644727 2025-05-01  221573934     Barry Phelps
27  7830347   12624464 2025-05-01  201528485     Ava Maximoff
28  7830348    7644741 2025-05-01  221573934     Barry Phelps
29  7830349   63658060 2025-05-01  218999613     June Ramirez

In [9]:
df.drop(columns=["rn"], inplace=True)
df.drop_duplicates(ignore_index=True, inplace=True)
df["rn"] = (
    df.sort_values(by="date", ascending=True)
    .groupby("user_id")
    .cumcount() + 1
)
df.sort_values(by= ["user_id", "date"]).head(30)

            date  user_id    user_name  rn
499   2025-05-01  8226413  Aeris Stone   1
2823  2025-05-05  8226413  Aeris Stone   2
3206  2025-05-06  8226413  Aeris Stone   3
3737  2025-05-07  8226413  Aeris Stone   4
10316 2025-05-21  8226413  Aeris Stone   5
10731 2025-05-22  8226413  Aeris Stone   6
11253 2025-05-23  8226413  Aeris Stone   7
13587 2025-05-28  8226413  Aeris Stone   8
14029 2025-05-29  8226413  Aeris Stone   9
16251 2025-06-03  8226413  Aeris Stone  10
16649 2025-06-04  8226413  Aeris Stone  11
17171 2025-06-05  8226413  Aeris Stone  12
18086 2025-06-07  8226413  Aeris Stone  13
18830 2025-06-09  8226413  Aeris Stone  14
19302 2025-06-10  8226413  Aeris Stone  15
19782 2025-06-11  8226413  Aeris Stone  16
20263 2025-06-12  8226413  Aeris Stone  17
21826 2025-06-16  8226413  Aeris Stone  18
22583 2025-06-17  8226413  Aeris Stone  19
25096 2025-06-23  8226413  Aeris Stone  20
25690 2025-06-24  8226413  Aeris Stone  21
26142 2025-06-25  8226413  Aeris Stone  22
27106 2025-06-27  8226413  Aeris Stone  23
34433 2025-07-14  8226413  Aeris Stone  24
35007 2025-07-15  8226413  Aeris Stone  25
35513 2025-07-16  8226413  Aeris Stone  26
36071 2025-07-17  8226413  Aeris Stone  27
37704 2025-07-21  8226413  Aeris Stone  28
38248 2025-07-22  8226413  Aeris Stone  29
38861 2025-07-23  8226413  Aeris Stone  30

In [12]:
df['streak_grp'] = df["date"] - pd.to_timedelta(df["rn"], unit= "D")
df.head(30)

         date    user_id        user_name  rn streak_grp
0  2025-05-01  205139497        Ike Pivot   1 2025-04-30
1  2025-05-01  210895353    Inosuke Ortiz   1 2025-04-30
2  2025-05-01  188456341  Hermione Miller   1 2025-04-30
3  2025-05-01  191335864     Piper Palmer   1 2025-04-30
4  2025-05-01  188981754    Indy Maverick   1 2025-04-30
5  2025-05-01  209588409    Vegeta Organa   1 2025-04-30
6  2025-05-01  173810415  Miles Targaryen   1 2025-04-30
7  2025-05-01  221324630       Kai Bailey   1 2025-04-30
8  2025-05-01  101731126       Goku Ortiz   1 2025-04-30
9  2025-05-01  125948590     Diana Nelson   1 2025-04-30
10 2025-05-01  200414107       Maya Perez   1 2025-04-30
11 2025-05-01   34006454      Sara Arnold   1 2025-04-30
12 2025-05-01   46994177     Rhodey Wells   1 2025-04-30
13 2025-05-01  208450551        Sara Ford   1 2025-04-30
14 2025-05-01  213946629     Ivy Mcdonald   1 2025-04-30
15 2025-05-01  221670783      Loki Miller   1 2025-04-30
16 2025-05-01  221318185       Zeke Mason   1 2025-04-30
17 2025-05-01   87295251  Hinata Ferguson   1 2025-04-30
18 2025-05-01  221573934     Barry Phelps   1 2025-04-30
19 2025-05-01  201528485     Ava Maximoff   1 2025-04-30
20 2025-05-01  218999613     June Ramirez   1 2025-04-30
21 2025-05-01  221261652      Kobe Bourne   1 2025-04-30
22 2025-05-01  219585350      Carol James   1 2025-04-30
23 2025-05-01  221088105   Mario Gonzalez   1 2025-04-30
24 2025-05-01  221671853    Zeke Reynolds   1 2025-04-30
25 2025-05-01   78645172       Mila Ellis   1 2025-04-30
26 2025-05-01  221540096     Gianni Davis   1 2025-04-30
27 2025-05-01   36034575       Otis Stark   1 2025-04-30
28 2025-05-01  207484162  Erwin Evergreen   1 2025-04-30
29 2025-05-01  219013014        Ava Pixel   1 2025-04-30

In [15]:
df_streaks = (
    df.groupby(["user_id", "streak_grp"])
    .agg({"user_name": "max" ,"date": ["min", "max"], "user_id": "count"})
)
df_streaks.columns = ["user_name", "start_date", "end_date", "streak_length"]
df_streaks

                            user_name start_date   end_date  streak_length
user_id   streak_grp
8226413   2025-04-30      Aeris Stone 2025-05-01 2025-05-01              1
          2025-05-03      Aeris Stone 2025-05-05 2025-05-07              3
          2025-05-16      Aeris Stone 2025-05-21 2025-05-23              3
          2025-05-20      Aeris Stone 2025-05-28 2025-05-29              2
          2025-05-24      Aeris Stone 2025-06-03 2025-06-05              3
...                               ...        ...        ...            ...
232470579 2025-09-27    Miles Vlookup 2025-09-28 2025-09-28              1
232472960 2025-09-27      Luna Malfoy 2025-09-28 2025-09-28              1
232473696 2025-09-27     Quinn Rivera 2025-09-28 2025-09-28              1
232473825 2025-09-27   Tchalla Zidane 2025-09-28 2025-09-28              1
232475177 2025-09-27  Vincent Thunder 2025-09-28 2025-09-28              1

[39179 rows x 4 columns]

In [19]:
active_streaks = df_streaks[df_streaks["end_date"]== "2025-09-28"].sort_values(by="streak_length", ascending=False)
active_streaks

                             user_name start_date   end_date  streak_length
user_id   streak_grp
84071240  2025-04-30      Stan Pancake 2025-05-01 2025-09-28            151
16814590  2025-05-12      Tom Parmesan 2025-05-31 2025-09-28            121
215518363 2025-05-10   Chuck Butternut 2025-06-01 2025-09-28            120
213142099 2025-05-27       Helen Melon 2025-06-25 2025-09-28             96
215121049 2025-05-11  Gertrude Strudel 2025-07-03 2025-09-28             88
...                                ...        ...        ...            ...
232458767 2025-09-27     Vincent Dixon 2025-09-28 2025-09-28              1
232472960 2025-09-27       Luna Malfoy 2025-09-28 2025-09-28              1
232473696 2025-09-27      Quinn Rivera 2025-09-28 2025-09-28              1
232473825 2025-09-27    Tchalla Zidane 2025-09-28 2025-09-28              1
232475177 2025-09-27   Vincent Thunder 2025-09-28 2025-09-28              1

[292 rows x 4 columns]