In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Etudes\projects\Python\Marketing Compaign\marketing_campaign_data_messy.csv",
                 parse_dates=["Start_Date","End_Date"])
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Campaign_ID   2020 non-null   str
 1   Campaign_Name  2020 non-null   str
 2   Start_Date     2020 non-null   str
 3   End_Date       2020 non-null   datetime64[us]
 4   Channel        1919 non-null   str
 5   Impressions    2020 non-null   int64
 6   Clicks         2020 non-null   int64
 7   Spend          2020 non-null   str
 8   Conversions    1820 non-null   float64
 9   Active         2020 non-null   str
 10  Clicks         40 non-null     float64
 11  Campaign_Tag   2020 non-null   str
dtypes: datetime64[us](1), float64(2), int64(2), str(7)
memory usage: 189.5 KB

In [3]:
# Cleaning Header
print(df.columns.to_list())
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print("Fix Applied:")
print(df.columns.to_list())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']
Fix Applied:
['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

In [4]:
# Type Conversion and Currency Cleaning
df["spend"] = df["spend"].replace(r"[^\d.]", "", regex=True).astype("float")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    2020 non-null   str
 1   campaign_name  2020 non-null   str
 2   start_date     2020 non-null   str
 3   end_date       2020 non-null   datetime64[us]
 4   channel        1919 non-null   str
 5   impressions    2020 non-null   int64
 6   clicks         2020 non-null   int64
 7   spend          2020 non-null   float64
 8   conversions    1820 non-null   float64
 9   active         2020 non-null   str
 10  clicks         40 non-null     float64
 11  campaign_tag   2020 non-null   str
dtypes: datetime64[us](1), float64(3), int64(2), str(6)
memory usage: 189.5 KB

In [5]:
# Categorical Typos
print(df["channel"].unique())
cleanup_map = {
    "Facebok": "Facebook",
    "Gogle": "Google Ads",
    "Tik_Tok": "TikTok",
    "E-mail": "Email",
    "Insta_gram": "Instagram",
    "N/A": np.nan
}
df["channel"] = df["channel"].replace(cleanup_map)

print("Fix Applied:")
print(df["channel"].unique())

<StringArray>
[    'TikTok',   'Facebook',      'Email',  'Instagram', 'Google Ads',
     'E-mail',          nan,      'Gogle',    'Tik_Tok',    'Facebok',
 'Insta_gram']
Length: 11, dtype: str
Fix Applied:
<StringArray>
['TikTok', 'Facebook', 'Email', 'Instagram', 'Google Ads', nan]
Length: 6, dtype: str

In [6]:
# Handling Mixed Booleans
print(df["active"].unique())

boolean_map = {
    "True": True,
    "Yes": True,
    "1": True,
    "Y": True,
    "0": False,
    "No": False
}
df["active"] = df["active"].replace(boolean_map).fillna(False).astype("bool")
print("Fix Applied:")
print(df["active"].unique())

<StringArray>
['Y', '0', 'No', 'True', 'Yes', '1', 'False']
Length: 7, dtype: str
Fix Applied:
[ True False]

In [7]:
# Dates Parsing
print(df["start_date"].dtype)

df["start_date"] = pd.to_datetime(df["start_date"], errors="coerce")
print("Fix Applied:")
print(df["start_date"].dtype)

str
Fix Applied:
datetime64[us]

In [8]:
df = df.loc[:, ~df.columns.duplicated()]

In [9]:
# Logical Integrity(clicks vs impressions)
impossible_mask = df["impressions"] < df["clicks"]
print(df.loc[impossible_mask, ["clicks", "impressions"]].head())

Empty DataFrame
Columns: [clicks, impressions]
Index: []

In [10]:
# Logical Integrity(time travel)
time_travel_mask = df["start_date"] > df["end_date"]
print(len(df.loc[time_travel_mask, ["start_date", "end_date"]]))
df["days_diff"] = (df["end_date"] - df["start_date"]).dt.days
correct_average = df.loc[df["days_diff"] >= 0, "days_diff"].mean()
wrong_average = df.loc[df["days_diff"] < 0, "days_diff"].mean()
print(f" Average days difference of correct values: {correct_average}")
print(f" Average days difference of wrong values: {wrong_average}")

# Assumption: in time travel_travel_mask start_date and end_date were inversed
df.loc[time_travel_mask, ["start_date", "end_date"]] = df.loc[time_travel_mask, ["end_date", "start_date"]].values
print("Fix Applied:")
print(df.loc[time_travel_mask, ["start_date", "end_date"]].head())
df.drop(columns=["days_diff"], inplace=True)

34
 Average days difference of correct values: 15.462189957652752
 Average days difference of wrong values: -5.0
Fix Applied:
    start_date   end_date
23  2023-05-01 2023-05-06
54  2023-08-27 2023-09-01
71  2023-01-27 2023-02-01
156 2023-12-01 2023-12-06
200 2023-01-06 2023-01-11

In [11]:
# Handling Outliers

Q1 = df["spend"].quantile(0.25)
Q3 = df["spend"].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + (3*IQR)

outlier_mask = df["spend"] > upper_limit
print(df.loc[outlier_mask, "spend"].head(3))

df.loc[outlier_mask, "spend"] =  upper_limit
print("Fix Applied:")
print(df.loc[outlier_mask, "spend"].head(3))

789     500000.00
1443      8921.51
1460    500000.00
Name: spend, dtype: float64
Fix Applied:
789     8576.8675
1443    8576.8675
1460    8576.8675
Name: spend, dtype: float64

In [12]:
# String Parsing

print(df["campaign_name"].head(3))

df["season"] = df["campaign_name"].str.split("_").str[1]
print("Fix Applied:")
print(df[["campaign_name", "season"]].head(3))

0    Q4_Summer_CMP-00001
1    Q1_Launch_CMP-00002
2    Q3_Winter_CMP-00003
Name: campaign_name, dtype: str
Fix Applied:
         campaign_name  season
0  Q4_Summer_CMP-00001  Summer
1  Q1_Launch_CMP-00002  Launch
2  Q3_Winter_CMP-00003  Winter

In [13]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag,season
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI,Summer
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA,Launch
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM,Winter
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI,BlackFriday
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI,Summer
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO,Summer
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN,Launch
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,FA,Winter
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM,Launch

In [14]:
df.to_csv("Marketing Campaign Clean", index=False)