In [1]:
import pandas as pd

df = pd.read_csv(
    r"C:\Etudes\projects\data drills maven\Cart Combos\grocery_transactions.csv",
    usecols=["transaction_id", "product_name"]
)
df.head()

   transaction_id product_name
0               1         Eggs
1               1         Milk
2               2     Parmesan
3               2        Pasta
4               2  Pasta Sauce

In [2]:
df["product_id"] = df["product_name"].rank(method="dense").astype(int)
df.head()

   transaction_id product_name  product_id
0               1         Eggs           9
1               1         Milk          19
2               2     Parmesan          23
3               2        Pasta          24
4               2  Pasta Sauce          25

In [7]:
df_merged = pd.merge(df, df, on="transaction_id", how="inner", suffixes=("_1", "_2"))
df_merged = df_merged.query("product_id_1 < product_id_2")
df_merged = df_merged.reset_index(drop=True)
df_merged.head()

   transaction_id product_name_1  product_id_1 product_name_2  product_id_2
0               1           Eggs             9           Milk            19
1               2       Parmesan            23          Pasta            24
2               2       Parmesan            23    Pasta Sauce            25
3               2       Parmesan            23         Yogurt            32
4               2          Pasta            24    Pasta Sauce            25

In [8]:
df_pairs = (
    df_merged
    .groupby(["product_name_1", "product_name_2"])
    .agg(number_of_transactions = ("transaction_id", "count"))
)
df_pairs.sort_values(by="number_of_transactions", ascending=False, inplace=True)
df_pairs

                               number_of_transactions
product_name_1 product_name_2
Salsa          Tortilla Chips                    5358
Bananas        Milk                              4483
               Bread                             2970
               Salsa                             2874
               Tortilla Chips                    2857
...                                               ...
Ketchup        Rice                                60
               Tomatoes                            60
Parmesan       Tomatoes                            59
Ketchup        Yogurt                              56
Frozen Pizza   Ketchup                             55

[391 rows x 1 columns]