In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Etudes\projects\data drills maven\Golden cross\SPY_close_price_5Y.csv", parse_dates=["Date"])
df.head(30)

         Date   Close
0  2020-11-02  330.20
1  2020-11-03  336.03
2  2020-11-04  343.54
3  2020-11-05  350.24
4  2020-11-06  350.16
5  2020-11-09  354.56
6  2020-11-10  354.04
7  2020-11-11  356.67
8  2020-11-12  353.21
9  2020-11-13  358.10
10 2020-11-16  362.57
11 2020-11-17  360.62
12 2020-11-18  356.28
13 2020-11-19  357.78
14 2020-11-20  355.33
15 2020-11-23  357.46
16 2020-11-24  363.22
17 2020-11-25  362.66
18 2020-11-27  363.67
19 2020-11-30  362.06
20 2020-12-01  366.02
21 2020-12-02  366.79
22 2020-12-03  366.69
23 2020-12-04  369.85
24 2020-12-07  369.09
25 2020-12-08  370.17
26 2020-12-09  366.85
27 2020-12-10  366.73
28 2020-12-11  366.30
29 2020-12-14  364.66

In [6]:
df["ma50"] = df["Close"].rolling(50).mean()
df["ma200"] = df["Close"].rolling(200).mean()
df.head(60)

         Date   Close      ma50  ma200
0  2020-11-02  330.20       NaN    NaN
1  2020-11-03  336.03       NaN    NaN
2  2020-11-04  343.54       NaN    NaN
3  2020-11-05  350.24       NaN    NaN
4  2020-11-06  350.16       NaN    NaN
5  2020-11-09  354.56       NaN    NaN
6  2020-11-10  354.04       NaN    NaN
7  2020-11-11  356.67       NaN    NaN
8  2020-11-12  353.21       NaN    NaN
9  2020-11-13  358.10       NaN    NaN
10 2020-11-16  362.57       NaN    NaN
11 2020-11-17  360.62       NaN    NaN
12 2020-11-18  356.28       NaN    NaN
13 2020-11-19  357.78       NaN    NaN
14 2020-11-20  355.33       NaN    NaN
15 2020-11-23  357.46       NaN    NaN
16 2020-11-24  363.22       NaN    NaN
17 2020-11-25  362.66       NaN    NaN
18 2020-11-27  363.67       NaN    NaN
19 2020-11-30  362.06       NaN    NaN
20 2020-12-01  366.02       NaN    NaN
21 2020-12-02  366.79       NaN    NaN
22 2020-12-03  366.69       NaN    NaN
23 2020-12-04  369.85       NaN    NaN
24 2020-12-07  369.09       NaN    NaN
25 2020-12-08  370.17       NaN    NaN
26 2020-12-09  366.85       NaN    NaN
27 2020-12-10  366.73       NaN    NaN
28 2020-12-11  366.30       NaN    NaN
29 2020-12-14  364.66       NaN    NaN
30 2020-12-15  369.59       NaN    NaN
31 2020-12-16  370.17       NaN    NaN
32 2020-12-17  372.24       NaN    NaN
33 2020-12-18  369.18       NaN    NaN
34 2020-12-21  367.86       NaN    NaN
35 2020-12-22  367.24       NaN    NaN
36 2020-12-23  367.57       NaN    NaN
37 2020-12-24  369.00       NaN    NaN
38 2020-12-28  372.17       NaN    NaN
39 2020-12-29  371.46       NaN    NaN
40 2020-12-30  371.99       NaN    NaN
41 2020-12-31  373.88       NaN    NaN
42 2021-01-04  368.79       NaN    NaN
43 2021-01-05  371.33       NaN    NaN
44 2021-01-06  373.55       NaN    NaN
45 2021-01-07  379.10       NaN    NaN
46 2021-01-08  381.26       NaN    NaN
47 2021-01-11  378.69       NaN    NaN
48 2021-01-12  378.77       NaN    NaN
49 2021-01-13  379.79  364.3036    NaN
50 2021-01-14  378.46  365.2688    NaN
51 2021-01-15  375.70  366.0622    NaN
52 2021-01-19  378.65  366.7644    NaN
53 2021-01-20  383.89  367.4374    NaN
54 2021-01-21  384.24  368.1190    NaN
55 2021-01-22  382.88  368.6854    NaN
56 2021-01-25  384.39  369.2924    NaN
57 2021-01-26  383.79  369.8348    NaN
58 2021-01-27  374.41  370.2588    NaN
59 2021-01-28  377.63  370.6494    NaN

In [7]:
df["lag_ma50"] = df["ma50"].shift(1)
df["lag_ma200"] = df["ma200"].shift(1)
df.head(60)

         Date   Close      ma50  ma200  lag_ma50  lag_ma200
0  2020-11-02  330.20       NaN    NaN       NaN        NaN
1  2020-11-03  336.03       NaN    NaN       NaN        NaN
2  2020-11-04  343.54       NaN    NaN       NaN        NaN
3  2020-11-05  350.24       NaN    NaN       NaN        NaN
4  2020-11-06  350.16       NaN    NaN       NaN        NaN
5  2020-11-09  354.56       NaN    NaN       NaN        NaN
6  2020-11-10  354.04       NaN    NaN       NaN        NaN
7  2020-11-11  356.67       NaN    NaN       NaN        NaN
8  2020-11-12  353.21       NaN    NaN       NaN        NaN
9  2020-11-13  358.10       NaN    NaN       NaN        NaN
10 2020-11-16  362.57       NaN    NaN       NaN        NaN
11 2020-11-17  360.62       NaN    NaN       NaN        NaN
12 2020-11-18  356.28       NaN    NaN       NaN        NaN
13 2020-11-19  357.78       NaN    NaN       NaN        NaN
14 2020-11-20  355.33       NaN    NaN       NaN        NaN
15 2020-11-23  357.46       NaN    NaN       NaN        NaN
16 2020-11-24  363.22       NaN    NaN       NaN        NaN
17 2020-11-25  362.66       NaN    NaN       NaN        NaN
18 2020-11-27  363.67       NaN    NaN       NaN        NaN
19 2020-11-30  362.06       NaN    NaN       NaN        NaN
20 2020-12-01  366.02       NaN    NaN       NaN        NaN
21 2020-12-02  366.79       NaN    NaN       NaN        NaN
22 2020-12-03  366.69       NaN    NaN       NaN        NaN
23 2020-12-04  369.85       NaN    NaN       NaN        NaN
24 2020-12-07  369.09       NaN    NaN       NaN        NaN
25 2020-12-08  370.17       NaN    NaN       NaN        NaN
26 2020-12-09  366.85       NaN    NaN       NaN        NaN
27 2020-12-10  366.73       NaN    NaN       NaN        NaN
28 2020-12-11  366.30       NaN    NaN       NaN        NaN
29 2020-12-14  364.66       NaN    NaN       NaN        NaN
30 2020-12-15  369.59       NaN    NaN       NaN        NaN
31 2020-12-16  370.17       NaN    NaN       NaN        NaN
32 2020-12-17  372.24       NaN    NaN       NaN        NaN
33 2020-12-18  369.18       NaN    NaN       NaN        NaN
34 2020-12-21  367.86       NaN    NaN       NaN        NaN
35 2020-12-22  367.24       NaN    NaN       NaN        NaN
36 2020-12-23  367.57       NaN    NaN       NaN        NaN
37 2020-12-24  369.00       NaN    NaN       NaN        NaN
38 2020-12-28  372.17       NaN    NaN       NaN        NaN
39 2020-12-29  371.46       NaN    NaN       NaN        NaN
40 2020-12-30  371.99       NaN    NaN       NaN        NaN
41 2020-12-31  373.88       NaN    NaN       NaN        NaN
42 2021-01-04  368.79       NaN    NaN       NaN        NaN
43 2021-01-05  371.33       NaN    NaN       NaN        NaN
44 2021-01-06  373.55       NaN    NaN       NaN        NaN
45 2021-01-07  379.10       NaN    NaN       NaN        NaN
46 2021-01-08  381.26       NaN    NaN       NaN        NaN
47 2021-01-11  378.69       NaN    NaN       NaN        NaN
48 2021-01-12  378.77       NaN    NaN       NaN        NaN
49 2021-01-13  379.79  364.3036    NaN       NaN        NaN
50 2021-01-14  378.46  365.2688    NaN  364.3036        NaN
51 2021-01-15  375.70  366.0622    NaN  365.2688        NaN
52 2021-01-19  378.65  366.7644    NaN  366.0622        NaN
53 2021-01-20  383.89  367.4374    NaN  366.7644        NaN
54 2021-01-21  384.24  368.1190    NaN  367.4374        NaN
55 2021-01-22  382.88  368.6854    NaN  368.1190        NaN
56 2021-01-25  384.39  369.2924    NaN  368.6854        NaN
57 2021-01-26  383.79  369.8348    NaN  369.2924        NaN
58 2021-01-27  374.41  370.2588    NaN  369.8348        NaN
59 2021-01-28  377.63  370.6494    NaN  370.2588        NaN

In [10]:
from numpy import where
df["golden_cross"] = where(
    (df["ma50"] > df["ma200"]) * (df["lag_ma50"] <= df["lag_ma200"]),
    1,
    0
)
df

,Date,Close,ma50,ma200,lag_ma50,lag_ma200,golden_cross
0,2020-11-02,330.20,NaN,NaN,NaN,NaN,0
1,2020-11-03,336.03,NaN,NaN,NaN,NaN,0
2,2020-11-04,343.54,NaN,NaN,NaN,NaN,0
3,2020-11-05,350.24,NaN,NaN,NaN,NaN,0
4,2020-11-06,350.16,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...
1251,2025-10-27,685.24,658.5806,607.44455,657.7446,606.96580,0
1252,2025-10-28,687.06,659.4558,607.97740,658.5806,607.44455,0
1253,2025-10-29,687.39,660.4074,608.50740,659.4558,607.97740,0
1254,2025-10-30,679.83,661.2418,608.99560,660.4074,608.50740,0
1255,2025-10-31,682.06,662.1720,609.44200,661.2418,608.99560,0

In [11]:
df.query("golden_cross == 1")

,Date,Close,ma50,ma200,lag_ma50,lag_ma200,golden_cross
566,2023-02-02,416.78,394.3504,394.25025,393.9354,394.3562,1
1169,2025-07-01,617.65,583.0978,582.04155,581.2730,581.7254,1