In [1]:
import numpy as np
import pandas as pd
df_estate = pd.read_csv(r"C:\Etudes\projects\data drills maven\Estimate The Estate\manhattan_property_sales.csv")
df_estate.head(20)

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000
5,CHELSEA,304 WEST 18TH STREET,10011,A4,3363,4775000
6,CHELSEA,224 WEST 22ND STREET,10011,A9,6715,10600000
7,CHELSEA,217 WEST 20 STREET,10011,A9,7805,11600000
8,GRAMERCY,143 EAST 18 STREET,10003,A4,3360,6400000
9,GRAMERCY,135 EAST 18TH STREET,10003,A4,3192,3850000
10,GRAMERCY,128 EAST 19 STREET,10003,A4,6060,6250000
11,GRAMERCY,135 EAST 19 STREET,10003,A4,6798,7400000
12,GRAMERCY,144 EAST 19TH STREET,10003,A4,2429,3800000
13,GREENWICH VILLAGE,38 WEST 12,10011,A4,5400,0
14,GREENWICH VILLAGE,110 WEST 13TH STREET,10011,A4,3640,9600000
15,GREENWICH VILLAGE,11 WEST 12TH ST,10011,A4,8125,26500000
16,GREENWICH VILLAGE,152 WEST 13 STREET,10011,A5,3381,18750000
17,GREENWICH VILLAGE,6 MAC DOUGAL ALLEY,10011,A9,1284,4660000
18,GREENWICH VILLAGE,19 DOWNING STREET,10014,A4,3166,9900000
19,GREENWICH VILLAGE,244 WEST 12TH ST,10014,A4,3416,13000000

In [4]:
df_estate["SALE_PRICE"] = np.where(df_estate["SALE_PRICE"]>0, df_estate["SALE_PRICE"], np.nan)
df_estate["price/sqrft"] = df_estate["SALE_PRICE"] / df_estate["SQUARE_FEET"]
df_estate["avg_price/sqrft"] = (
    df_estate
    .groupby(["ZIP_CODE", "BUILDING_CLASS"])["price/sqrft"]
    .transform("mean")
)
df_estate.head(20)

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,price/sqrft,avg_price/sqrft
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999.0,1667.222296,2668.274136
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000.0,4437.869822,2668.274136
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000.0,2273.402675,2668.274136
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,NaN,NaN,2668.274136
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000.0,2980.659841,2668.274136
5,CHELSEA,304 WEST 18TH STREET,10011,A4,3363,4775000.0,1419.863217,2668.274136
6,CHELSEA,224 WEST 22ND STREET,10011,A9,6715,10600000.0,1578.555473,2231.355247
7,CHELSEA,217 WEST 20 STREET,10011,A9,7805,11600000.0,1486.226778,2231.355247
8,GRAMERCY,143 EAST 18 STREET,10003,A4,3360,6400000.0,1904.761905,1359.048131
9,GRAMERCY,135 EAST 18TH STREET,10003,A4,3192,3850000.0,1206.140351,1359.048131
10,GRAMERCY,128 EAST 19 STREET,10003,A4,6060,6250000.0,1031.353135,1359.048131
11,GRAMERCY,135 EAST 19 STREET,10003,A4,6798,7400000.0,1088.555457,1359.048131
12,GRAMERCY,144 EAST 19TH STREET,10003,A4,2429,3800000.0,1564.429807,1359.048131
13,GREENWICH VILLAGE,38 WEST 12,10011,A4,5400,NaN,NaN,2668.274136
14,GREENWICH VILLAGE,110 WEST 13TH STREET,10011,A4,3640,9600000.0,2637.362637,2668.274136
15,GREENWICH VILLAGE,11 WEST 12TH ST,10011,A4,8125,26500000.0,3261.538462,2668.274136
16,GREENWICH VILLAGE,152 WEST 13 STREET,10011,A5,3381,18750000.0,5545.696539,5545.696539
17,GREENWICH VILLAGE,6 MAC DOUGAL ALLEY,10011,A9,1284,4660000.0,3629.283489,2231.355247
18,GREENWICH VILLAGE,19 DOWNING STREET,10014,A4,3166,9900000.0,3126.974100,4047.938711
19,GREENWICH VILLAGE,244 WEST 12TH ST,10014,A4,3416,13000000.0,3805.620609,4047.938711

In [5]:
df_estate["market_value"] = np.where(df_estate["SALE_PRICE"]>0,
                                     df_estate["SALE_PRICE"],
                                     df_estate["avg_price/sqrft"]*df_estate["SQUARE_FEET"])
df_estate.head(20)

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,price/sqrft,avg_price/sqrft,market_value
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999.0,1667.222296,2668.274136,1.500000e+07
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000.0,4437.869822,2668.274136,1.350000e+07
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000.0,2273.402675,2668.274136,7.650000e+06
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,NaN,NaN,2668.274136,9.781893e+06
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000.0,2980.659841,2668.274136,1.310000e+07
5,CHELSEA,304 WEST 18TH STREET,10011,A4,3363,4775000.0,1419.863217,2668.274136,4.775000e+06
6,CHELSEA,224 WEST 22ND STREET,10011,A9,6715,10600000.0,1578.555473,2231.355247,1.060000e+07
7,CHELSEA,217 WEST 20 STREET,10011,A9,7805,11600000.0,1486.226778,2231.355247,1.160000e+07
8,GRAMERCY,143 EAST 18 STREET,10003,A4,3360,6400000.0,1904.761905,1359.048131,6.400000e+06
9,GRAMERCY,135 EAST 18TH STREET,10003,A4,3192,3850000.0,1206.140351,1359.048131,3.850000e+06
10,GRAMERCY,128 EAST 19 STREET,10003,A4,6060,6250000.0,1031.353135,1359.048131,6.250000e+06
11,GRAMERCY,135 EAST 19 STREET,10003,A4,6798,7400000.0,1088.555457,1359.048131,7.400000e+06
12,GRAMERCY,144 EAST 19TH STREET,10003,A4,2429,3800000.0,1564.429807,1359.048131,3.800000e+06
13,GREENWICH VILLAGE,38 WEST 12,10011,A4,5400,NaN,NaN,2668.274136,1.440868e+07
14,GREENWICH VILLAGE,110 WEST 13TH STREET,10011,A4,3640,9600000.0,2637.362637,2668.274136,9.600000e+06
15,GREENWICH VILLAGE,11 WEST 12TH ST,10011,A4,8125,26500000.0,3261.538462,2668.274136,2.650000e+07
16,GREENWICH VILLAGE,152 WEST 13 STREET,10011,A5,3381,18750000.0,5545.696539,5545.696539,1.875000e+07
17,GREENWICH VILLAGE,6 MAC DOUGAL ALLEY,10011,A9,1284,4660000.0,3629.283489,2231.355247,4.660000e+06
18,GREENWICH VILLAGE,19 DOWNING STREET,10014,A4,3166,9900000.0,3126.974100,4047.938711,9.900000e+06
19,GREENWICH VILLAGE,244 WEST 12TH ST,10014,A4,3416,13000000.0,3805.620609,4047.938711,1.300000e+07

In [6]:
# number of estates with a market value over 15M
print(len(df_estate[df_estate["market_value"]>15000000]))

19